' Windowless launcher for the nightly self-improvement pass. Generated by
' register_selfimprove_nightly.ps1 -- edit that, not this.
' 0 = hidden window, False = do not wait.
Set sh = CreateObject("WScript.Shell")
sh.CurrentDirectory = "C:\Users\USER\resonac-mcp"
sh.Run """C:\Users\USER\resonac-mcp\.venv\Scripts\python.exe"" ""C:\Users\USER\resonac-mcp\scripts\selfimprove_driver.py""", 0, False